version: "2"

services:
  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: m584023958usojfs4z2fzfjy
      MONGODB_DATABASE: blog
    container_name: blog
    ports:
      - "27017:27017"
    volumes:
    - mongodb:/data/db

volumes:
  mongodb:
    driver: local